name: Publish Docker Image

env:
  IMAGE_NAME: "jdlubrano/terraform-aws-ci"
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build --no-cache --pull . --tag $IMAGE_NAME:latest
      - name: Docker login
        run: docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
      - name: Publish the latest tag
        if: startsWith(github.ref, 'refs/heads/')
        run: docker push $IMAGE_NAME:latest
      - name: Tag the image with the semver
        if: startsWith(github.ref, 'refs/tags/')
        run: docker tag $IMAGE_NAME:latest $IMAGE_NAME:${GITHUB_REF#refs/*/}
      - name: Publish the semver tag
        if: startsWith(github.ref, 'refs/tags/')
        run: docker push $IMAGE_NAME:${GITHUB_REF#refs/*/}

