name: Docker Image CI

env:
  IMAGE_TAG: ghcr.io/jdlubrano/terraform-aws-ci:build-${{ github.run_number }}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint_dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: Dockerfile

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag $IMAGE_TAG

      - name: Push to GitHub Container Registry
        run: docker push $IMAGE_TAG

  test_github_action_viability:
    needs: [build]
    runs-on: ubuntu-latest
    container: ghcr.io/jdlubrano/terraform-aws-ci:build-${{ github.run_number }}
    steps:
      - uses: actions/checkout@v2

      - name: Go to example
        run: cd examples/github-actions/it-works

      - name: Test for aws and terraform executables
        run: ./test_executables.sh
