name: Docker Image CI

env:
  IMAGE_TAG: ghcr.io/jdlubrano/terraform-aws-ci:build-${{ github.run_number }}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint_dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: Dockerfile

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag $IMAGE_TAG

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Container Registry
        run: docker push $IMAGE_TAG

  security_scan:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Scan the Docker image
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ env.IMAGE_TAG }}


  test_github_action_viability:
    needs: [build]
    runs-on: ubuntu-latest
    container: ghcr.io/jdlubrano/terraform-aws-ci:build-${{ github.run_number }}
    steps:
      - uses: actions/checkout@v2

      - name: Verify that aws and terraform are available
        run: cd examples/github-actions/it-works && ./test_executables.sh
