name: Pick up Security Patches

env:
  IMAGE_TAG: ghcr.io/jdlubrano/terraform-aws-ci:build-${{ github.run_number }}

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build . --no-cache --pull --file Dockerfile --tag $IMAGE_TAG

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Container Registry
        run: docker push $IMAGE_TAG

  security_scan:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Scan the Docker image
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ env.IMAGE_TAG }}

  test_github_action_viability:
    needs: [build]
    runs-on: ubuntu-latest
    container: ghcr.io/jdlubrano/terraform-aws-ci:build-${{ github.run_number }}
    steps:
      - uses: actions/checkout@v2

      - name: Verify that aws and terraform are available
        run: cd examples/github-actions/it-works && ./test_executables.sh

  trigger_docker_publish:
    needs: [security_scan, test_github_action_viability]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install bump version
        run: pip install --upgrade bump2version

      - name: Bump version and push to main
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          bumpversion patch && cat VERSION
          git push -u origin main --tags
